### ISSUE TITLE
./configure: 594: dynlink_subdir: parameter not set or null

### ISSUE THREAD

**Issue by gerdstolpmann** [ocaml/ocamlfind#90] opened 2024-11-08 13:24 UTC
See https://github.com/Homebrew/homebrew-core/pull/196879/checks

Should check whether `dynlink_subdir` is set before using it.

**Comment by atsampson** [comment] 2024-11-08 15:40
This is a duplicate of #88.

**Closed** 2024-11-16 22:51 UTC
